### ISSUE TITLE
H Series 2014 not working

### ISSUE THREAD

**Issue by Spoocs** [iobroker-community-adapters/ioBroker.samsung-community#13]
As written on main page Samsung TVs between 2014 and 2016 will not work. It would be great, if support for those TVs can be added by overtaking pairing and crypto routines of homesung-homebridge repository.
Is there a chance to get this done?

**Comment by Apollon77** [comment]
Did you tried ham adapter and use this homebridge plugin then?

**Comment by Spoocs** [comment]
No, but others. 

https://www.reddit.com/r/homebridge/comments/9e3dz5/homebridge_plugin_to_control_samsung_smart_tv_h/

They only have issues with switching on/off

**Comment by Spoocs** [comment]
Attached you find a Python solution that was created the last two years, that also works with H-series including switch ing on and off.

https://github.com/tdudek/samsung-remote-models-2014-and-newer

**Comment by Spoocs** [comment]
homesung module works but it is a challenge to make it work with Iobroker HAM Plugin, as for pairing it is necessary to get an input field and forward the pin of TV screen. Due to this I had to install homebridge in another docker to pair and then take the config.json with the generated key for ham in wrapper mode. I also run iobroker in Container station of my Qunap. That is why I can not use the other HAM modes but maybe I‘m wrong as I am new to iobroker and homebridge as well.
Additionally the homesung module does not allow Power on. 
Due to those facts it would be great if you could overtake logic from homesung including pairing as separate mode for Samsung model between 2014 and 2016. Maybe the power on logic of iobroket module also supports h series.
What do you think?

**Comment by jogibear9988** [comment]
@Spoocs 
maybe you try ma new changes in the adpater

**Comment by Spoocs** [comment]
@jogibear9988 For my 2014 H-Model it is still not working. For this TVs you need first a pairing process with the TV. The pairing is still missing. Without the pairing the application and client do not get authorized. The pairing you can find in the links I have posted before.

**Comment by Spoocs** [comment]
Sorry I pressed the wrong button, therefor I closed the issue. I tried out this solution and it does the pairing perfectly: https://github.com/tdudek/samsung-remote-models-2014-and-newer. The generated token can then be used for the next sessions. Thge only issue is I'm not so used to JS and not so well in the interfaces of iobroker but willing to support you with testing and with giving you information on which APIs you can find what. Also the port should be changeable for this version.

**Comment by Spoocs** [comment]
@jogibear9988 
Sorry I pressed the wrong button, therefor I closed the issue. I tried out this solution and it does the pairing perfectly: https://github.com/tdudek/samsung-remote-models-2014-and-newer. The generated token can then be used for the next sessions. Thge only issue is I'm not so used to JS and not so well in the interfaces of iobroker but willing to support you with testing and with giving you information on which APIs you can find what. Also the port should be changeable for this version.

**Comment by Spoocs** [comment]
In the repository
https://github.com/tdudek/samsung-remote-models-2014-and-newer

in the following direwctory you find the pairing script:
samsung-remote-models-2014-and-newer/lib/Pairing/

This script must be executed for every TV once. The created Token can tbe used in all following session. For the pairing the end user gets a pin shown on the TV screen, this pin must be entered during the pairing process. After the pairing is done the following sessions use the created token.

**Comment by jogibear9988** [comment]
have you tried the github version?
and used samsungtv as api ?
you shoul then get a token in the log

**Comment by Spoocs** [comment]
I used Github version 0.4.0
I used Samsung TV API
This is the log

2020-05-06 00:03:39.031 - info: host.IOBrokerServer "system.adapter.samsung-community.0" enabled
--
2020-05-06 00:03:39.053 - info: host.IOBrokerServer instance system.adapter.samsung-community.0 started with pid 1297
2020-05-06 00:03:41.224 - info: samsung-community.0 (1297) starting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.samsung-community, node: v10.20.1
2020-05-06 00:05:13.142 - info: host.IOBrokerServer "system.adapter.samsung-community.0" disabled
2020-05-06 00:05:13.143 - info: host.IOBrokerServer stopInstance system.adapter.samsung-community.0 (force=false, process=true)
2020-05-06 00:05:13.144 - info: host.IOBrokerServer stopInstance system.adapter.samsung-community.0 send kill signal
2020-05-06 00:05:13.146 - info: samsung-community.0 (1297) Got terminate signal TERMINATE_YOURSELF
2020-05-06 00:05:13.147 - info: samsung-community.0 (1297) terminating
2020-05-06 00:05:13.148 - info: samsung-community.0 (1297) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
2020-05-06 00:05:13.664 - info: host.IOBrokerServer instance system.adapter.samsung-community.0 terminated with code 156 (156)
2020-05-06 00:05:14.829 - info: host.IOBrokerServer "system.adapter.samsung-community.0" enabled
2020-05-06 00:05:14.849 - info: host.IOBrokerServer instance system.adapter.samsung-community.0 started with pid 1328
2020-05-06 00:05:17.131 - info: samsung-community.0 (1328) starting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.samsung-community, node: v10.20.1
2020-05-06 00:05:17.485 - error: samsung-community.0 (1328) uncaught exception: connect ECONNREFUSED 192.168.0.13:8002
2020-05-06 00:05:17.486 - error: samsung-community.0 (1328) Error: connect ECONNREFUSED 192.168.0.13:8002
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-05-06 00:05:17.492 - info: samsung-community.0 (1328) terminating
2020-05-06 00:05:17.493 - info: samsung-community.0 (1328) Terminated (NO_ERROR): Without reason
2020-05-06 00:05:18.012 - error: host.IOBrokerServer Caught by controller[0]: info
2020-05-06 00:05:18.061 - error: host.IOBrokerServer Caught by controller[1]:
2020-05-06 00:05:18.062 - error: host.IOBrokerServer Caught by controller[2]: SamsungRemote Get device info from http://192.168.0.13:8001/api/v2/
2020-05-06 00:05:18.062 - error: host.IOBrokerServer Caught by controller[3]: info
2020-05-06 00:05:18.062 - error: host.IOBrokerServer Caught by controller[4]: SamsungRemote Connect to wss://192.168.0.13:8002/api/v2/channels/samsung.remote.control?name=aW9Ccm9rZXI=
2020-05-06 00:05:18.062 - error: host.IOBrokerServer Caught by controller[5]: { Error: connect ECONNREFUSED 192.168.0.13:8002
2020-05-06 00:05:18.062 - error: host.IOBrokerServer Caught by controller[5]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-05-06 00:05:18.063 - error: host.IOBrokerServer Caught by controller[5]: errno: 'ECONNREFUSED',
2020-05-06 00:05:18.063 - error: host.IOBrokerServer Caught by controller[5]: code: 'ECONNREFUSED',
2020-05-06 00:05:18.063 - error: host.IOBrokerServer Caught by controller[5]: syscall: 'connect',
2020-05-06 00:05:18.063 - error: host.IOBrokerServer Caught by controller[5]: address: '192.168.0.13',
2020-05-06 00:05:18.063 - error: host.IOBrokerServer Caught by controller[5]: port: 8002 }
2020-05-06 00:05:18.064 - info: host.IOBrokerServer instance system.adapter.samsung-community.0 terminated with code 0 (NO_ERROR)
2020-05-06 00:05:18.064 - info: host.IOBrokerServer Restart adapter system.adapter.samsung-community.0 because enabled
2020-05-06 00:05:48.082 - info: host.IOBrokerServer instance system.adapter.samsung-community.0 started with pid 1346
2020-05-06 00:05:50.441 - info: samsung-community.0 (1346) starting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.samsung-community, node: v10.20.1
2020-05-06 00:05:50.715 - error: samsung-community.0 (1346) uncaught exception: connect ECONNREFUSED 192.168.0.13:8002
2020-05-06 00:05:50.716 - error: samsung-community.0 (1346) Error: connect ECONNREFUSED 192.168.0.13:8002
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-05-06 00:05:50.763 - info: samsung-community.0 (1346) terminating
2020-05-06 00:05:50.764 - info: samsung-community.0 (1346) Terminated (NO_ERROR): Without reason
2020-05-06 00:05:51.283 - error: host.IOBrokerServer Caught by controller[0]: info
2020-05-06 00:05:51.283 - error: host.IOBrokerServer Caught by controller[1]:
2020-05-06 00:05:51.283 - error: host.IOBrokerServer Caught by controller[2]: SamsungRemote
2020-05-06 00:05:51.284 - error: host.IOBrokerServer Caught by controller[3]: Get device info from http://192.168.0.13:8001/api/v2/
2020-05-06 00:05:51.284 - error: host.IOBrokerServer Caught by controller[4]: info
2020-05-06 00:05:51.284 - error: host.IOBrokerServer Caught by controller[5]: SamsungRemote Connect to wss://192.168.0.13:8002/api/v2/channels/samsung.remote.control?name=aW9Ccm9rZXI=
2020-05-06 00:05:51.284 - error: host.IOBrokerServer Caught by controller[6]: { Error: connect ECONNREFUSED 192.168.0.13:8002
2020-05-06 00:05:51.284 - error: host.IOBrokerServer Caught by controller[6]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-05-06 00:05:51.285 - error: host.IOBrokerServer Caught by controller[6]: errno: 'ECONNREFUSED',
2020-05-06 00:05:51.285 - error: host.IOBrokerServer Caught by controller[6]: code: 'ECONNREFUSED',
2020-05-06 00:05:51.285 - error: host.IOBrokerServer Caught by controller[6]: syscall: 'connect',
2020-05-06 00:05:51.285 - error: host.IOBrokerServer Caught by controller[6]: address: '192.168.0.13',
2020-05-06 00:05:51.285 - error: host.IOBrokerServer Caught by controller[6]: port: 8002 }
2020-05-06 00:05:51.286 - info: host.IOBrokerServer instance system.adapter.samsung-community.0 terminated with code 0 (NO_ERROR)
2020-05-06 00:05:51.286 - info: host.IOBrokerServer Restart adapter system.adapter.samsung-community.0 because enabled
2020-05-06 00:06:21.305 - info: host.IOBrokerServer instance system.adapter.samsung-community.0 started with pid 1375
2020-05-06 00:06:24.087 - info: samsung-community.0 (1375) starting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.samsung-community, node: v10.20.1
2020-05-06 00:06:24.356 - error: samsung-community.0 (1375) uncaught exception: connect ECONNREFUSED 192.168.0.13:8002
2020-05-06 00:06:24.357 - error: samsung-community.0 (1375) Error: connect ECONNREFUSED 192.168.0.13:8002
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-05-06 00:06:24.403 - info: samsung-community.0 (1375) terminating
2020-05-06 00:06:24.405 - info: samsung-community.0 (1375) Terminated (NO_ERROR): Without reason
2020-05-06 00:06:24.961 - error: host.IOBrokerServer Caught by controller[0]: info
2020-05-06 00:06:24.962 - error: host.IOBrokerServer Caught by controller[1]:
2020-05-06 00:06:24.962 - error: host.IOBrokerServer Caught by controller[2]: SamsungRemote Get device info from http://192.168.0.13:8001/api/v2/
2020-05-06 00:06:24.962 - error: host.IOBrokerServer Caught by controller[3]: info
2020-05-06 00:06:24.962 - error: host.IOBrokerServer Caught by controller[4]: SamsungRemote Connect to wss://192.168.0.13:8002/api/v2/channels/samsung.remote.control?name=aW9Ccm9rZXI=
2020-05-06 00:06:24.963 - error: host.IOBrokerServer Caught by controller[5]: { Error: connect ECONNREFUSED 192.168.0.13:8002
2020-05-06 00:06:24.963 - error: host.IOBrokerServer Caught by controller[5]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-05-06 00:06:24.963 - error: host.IOBrokerServer Caught by controller[5]: errno: 'ECONNREFUSED',
2020-05-06 00:06:24.963 - error: host.IOBrokerServer Caught by controller[5]: code: 'ECONNREFUSED',
2020-05-06 00:06:24.963 - error: host.IOBrokerServer Caught by controller[5]: syscall: 'connect',
2020-05-06 00:06:24.964 - error: host.IOBrokerServer Caught by controller[5]: address: '192.168.0.13',
2020-05-06 00:06:24.964 - error: host.IOBrokerServer Caught by controller[5]: port: 8002 }
2020-05-06 00:06:24.964 - info: host.IOBrokerServer instance system.adapter.samsung-community.0 terminated with code 0 (NO_ERROR)
2020-05-06 00:06:24.964 - info: host.IOBrokerServer Restart adapter system.adapter.samsung-community.0 because enabled
2020-05-06 00:06:54.983 - info: host.IOBrokerServer instance system.adapter.samsung-community.0 started with pid 1390
2020-05-06 00:06:57.345 - info: samsung-community.0 (1390) starting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.samsung-community, node: v10.20.1
2020-05-06 00:06:57.588 - error: samsung-community.0 (1390) uncaught exception: connect ECONNREFUSED 192.168.0.13:8002
2020-05-06 00:06:57.588 - error: samsung-community.0 (1390) Error: connect ECONNREFUSED 192.168.0.13:8002
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-05-06 00:06:57.635 - info: samsung-community.0 (1390) terminating
2020-05-06 00:06:57.636 - info: samsung-community.0 (1390) Terminated (NO_ERROR): Without reason
2020-05-06 00:06:58.174 - error: host.IOBrokerServer Caught by controller[0]: info
2020-05-06 00:06:58.174 - error: host.IOBrokerServer Caught by controller[1]:
2020-05-06 00:06:58.174 - error: host.IOBrokerServer Caught by controller[2]: SamsungRemote Get device info from http://192.168.0.13:8001/api/v2/
2020-05-06 00:06:58.174 - error: host.IOBrokerServer Caught by controller[3]: info
2020-05-06 00:06:58.175 - error: host.IOBrokerServer Caught by controller[4]: SamsungRemote Connect to wss://192.168.0.13:8002/api/v2/channels/samsung.remote.control?name=aW9Ccm9rZXI=
2020-05-06 00:06:58.175 - error: host.IOBrokerServer Caught by controller[5]: { Error: connect ECONNREFUSED 192.168.0.13:8002
2020-05-06 00:06:58.175 - error: host.IOBrokerServer Caught by controller[5]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-05-06 00:06:58.175 - error: host.IOBrokerServer Caught by controller[5]: errno: 'ECONNREFUSED',
2020-05-06 00:06:58.175 - error: host.IOBrokerServer Caught by controller[5]: code: 'ECONNREFUSED',
2020-05-06 00:06:58.176 - error: host.IOBrokerServer Caught by controller[5]: syscall: 'connect',
2020-05-06 00:06:58.176 - error: host.IOBrokerServer Caught by controller[5]: address: '192.168.0.13',
2020-05-06 00:06:58.176 - error: host.IOBrokerServer Caught by controller[5]: port: 8002 }
2020-05-06 00:06:58.176 - info: host.IOBrokerServer instance system.adapter.samsung-community.0 terminated with code 0 (NO_ERROR)
2020-05-06 00:06:58.176 - info: host.IOBrokerServer Restart adapter system.adapter.samsung-community.0 because enabled
2020-05-06 00:07:28.195 - info: host.IOBrokerServer instance system.adapter.samsung-community.0 started with pid 1432
2020-05-06 00:07:30.449 - info: samsung-community.0 (1432) starting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.samsung-community, node: v10.20.1
2020-05-06 00:07:30.686 - error: samsung-community.0 (1432) uncaught exception: connect ECONNREFUSED 192.168.0.13:8002
2020-05-06 00:07:30.688 - error: samsung-community.0 (1432) Error: connect ECONNREFUSED 192.168.0.13:8002
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-05-06 00:07:30.734 - info: samsung-community.0 (1432) terminating
2020-05-06 00:07:30.735 - info: samsung-community.0 (1432) Terminated (NO_ERROR): Without reason
2020-05-06 00:07:31.254 - error: host.IOBrokerServer Caught by controller[0]: info
2020-05-06 00:07:31.255 - error: host.IOBrokerServer Caught by controller[1]:
2020-05-06 00:07:31.255 - error: host.IOBrokerServer Caught by controller[2]: SamsungRemote Get device info from http://192.168.0.13:8001/api/v2/
2020-05-06 00:07:31.257 - error: host.IOBrokerServer Caught by controller[3]: info SamsungRemote Connect to wss://192.168.0.13:8002/api/v2/channels/samsung.remote.control?name=aW9Ccm9rZXI=
2020-05-06 00:07:31.257 - error: host.IOBrokerServer Caught by controller[4]: { Error: connect ECONNREFUSED 192.168.0.13:8002
2020-05-06 00:07:31.257 - error: host.IOBrokerServer Caught by controller[4]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-05-06 00:07:31.257 - error: host.IOBrokerServer Caught by controller[4]: errno: 'ECONNREFUSED',
2020-05-06 00:07:31.258 - error: host.IOBrokerServer Caught by controller[4]: code: 'ECONNREFUSED',
2020-05-06 00:07:31.258 - error: host.IOBrokerServer Caught by controller[4]: syscall: 'connect',
2020-05-06 00:07:31.258 - error: host.IOBrokerServer Caught by controller[4]: address: '192.168.0.13',
2020-05-06 00:07:31.258 - error: host.IOBrokerServer Caught by controller[4]: port: 8002 }
2020-05-06 00:07:31.258 - info: host.IOBrokerServer instance system.adapter.samsung-community.0 terminated with code 0 (NO_ERROR)
2020-05-06 00:07:31.259 - info: host.IOBrokerServer Restart adapter system.adapter.samsung-community.0 because enabled
2020-05-06 00:08:01.278 - info: host.IOBrokerServer instance system.adapter.samsung-community.0 started with pid 1447
2020-05-06 00:08:03.417 - info: samsung-community.0 (1447) starting. Version 0.4.0 in /opt/iobroker/node_modules/iobroker.samsung-community, node: v10.20.1
2020-05-06 00:08:03.664 - error: samsung-community.0 (1447) uncaught exception: connect ECONNREFUSED 192.168.0.13:8002
2020-05-06 00:08:03.666 - error: samsung-community.0 (1447) Error: connect ECONNREFUSED 192.168.0.13:8002
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-05-06 00:08:03.714 - info: samsung-community.0 (1447) terminating
2020-05-06 00:08:03.715 - info: samsung-community.0 (1447) Terminated (NO_ERROR): Without reason
2020-05-06 00:08:04.233 - error: host.IOBrokerServer Caught by controller[0]: info
2020-05-06 00:08:04.234 - error: host.IOBrokerServer Caught by controller[1]:
2020-05-06 00:08:04.234 - error: host.IOBrokerServer Caught by controller[2]: SamsungRemote
2020-05-06 00:08:04.234 - error: host.IOBrokerServer Caught by controller[3]: Get device info from http://192.168.0.13:8001/api/v2/
2020-05-06 00:08:04.234 - error: host.IOBrokerServer Caught by controller[4]: info
2020-05-06 00:08:04.234 - error: host.IOBrokerServer Caught by controller[5]: SamsungRemote Connect to wss://192.168.0.13:8002/api/v2/channels/samsung.remote.control?name=aW9Ccm9rZXI=
2020-05-06 00:08:04.235 - error: host.IOBrokerServer Caught by controller[6]: { Error: connect ECONNREFUSED 192.168.0.13:8002
2020-05-06 00:08:04.235 - error: host.IOBrokerServer Caught by controller[6]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
2020-05-06 00:08:04.235 - error: host.IOBrokerServer Caught by controller[6]: errno: 'ECONNREFUSED',
2020-05-06 00:08:04.235 - error: host.IOBrokerServer Caught by controller[6]: code: 'ECONNREFUSED',
2020-05-06 00:08:04.235 - error: host.IOBrokerServer Caught by controller[6]: syscall: 'connect',
2020-05-06 00:08:04.236 - error: host.IOBrokerServer Caught by controller[6]: address: '192.168.0.13',
2020-05-06 00:08:04.236 - error: host.IOBrokerServer Caught by controller[6]: port: 8002 }
2020-05-06 00:08:04.236 - info: host.IOBrokerServer instance system.adapter.samsung-community.0 terminated with code 0 (NO_ERROR)
2020-05-06 00:08:04.236 - info: host.IOBrokerServer Restart adapter system.adapter.samsung-community.0 because enabled
